//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWeb.ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int HistoryID { get; set; }
        public System.DateTime ConsultationDate { get; set; }
        public string Notes { get; set; }
        public int AppointmentId { get; set; }
    
        public virtual Appointments Appointments { get; set; }
    }
}
