//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWeb.ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    
        public virtual Appointments Appointments { get; set; }
        public virtual Users Users { get; set; }
    }
}
