//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWeb.ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordRecovery
    {
        public int PasswordRecoveryID { get; set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
